# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Overload' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for Overload
    # pod 'SwiftPing', :git => 'git@github.com:ankitthakur/SwiftPing.git', :commit => '48a615bc1da7e3e4cdf86bff5b1b9b025d18e04e'
    pod 'PlainPing', :git => 'git@github.com:naptics/PlainPing.git', :commit => 'f2f13a898ba64b106ca33e5a5d4d2c9ddde827ad'
    # pod 'AlecrimAsyncKit', '~> 3.0'
end
